name: Pull Request Main Review

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
jobs:
  integration-test:
    runs-on: ubuntu-latest
    name: Integration Test
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v16.13.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.1
      - name: Init website
        run: |
          cd frontend
          npm install
          npm start &
      - name: Set up Docker Network
        run: docker network create -d bridge ias_net
      - name: Build the Docker image
        run: |
          cd database
          docker-compose up --build -d
      - name: Wait for Database
        run: |
          cd database
          while ! docker-compose logs | grep "ready for connections"; do
            echo "Waiting for initdb to complete..."
            sleep 5
          done
          sleep 5
      - name: Use Node.js v16.13.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.1
      - name: Install Node Packages
        run: |
          cd backend
          npm install
          npm start &
      - name: Use Python v3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Libraries
        run: |
          pip install pytest pytest-cov webdriver-manager selenium
      - name: Check Test Files Existence
        id: check_test_exists
        uses: andstor/file-existence-action@v2
        with:
          files: "integrationTest/test_*.py"
      - name: Test with Pytest
        if: steps.check_test_exists.outputs.files_exists == 'true'
        run: |
          #only run pytest when test_*.py exists
          for file in $(find . -name "test_*.py"); do
            cd database
            docker-compose down --volumes && docker-compose up --build -d
            while ! docker-compose logs | grep "ready for connections"; do
              echo "Waiting for initdb to complete..."
              sleep 5
            done
            sleep 5
            echo $file
            cd ../integrationTest
            pytest $file -v -cov --junitxml=test_report.xml
          done
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          check_name: "Integration Test Results"
          junit_files: "integrationTesting/test_report.xml"
  send-email:
    runs-on: ubuntu-latest
    name: Send Message
    needs: [integration-test]
    steps:
      - name: send telegram message on PR
        uses: appleboy/telegram-action@master
        with:
          to: "-827526484"
          token: "5669366185:AAFQ0KZ61oJxnh73V0Ove0-RiWY4LKbvx5I"
          message: |
            Pull request made to main.

            PR Owner: ${{ github.actor }}
            PR message: ${{ github.event.pull_request.title }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/pull/${{github.event.number}}
